default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "#{ENV["HOME"]}/.appstoreconnect/private_keys/AuthKey_#{ENV["APP_STORE_CONNECT_API_KEY_ID"]}.p8",
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier: "com.donsnotes.app",
      git_url: "https://github.com/dkgrissom-tech/ios-certificates",
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      readonly: false,
      api_key: api_key
    )

    build_app(
      scheme: "DonsNotes",
      project: "DonsNotes.xcodeproj",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "DonsNotes.ipa"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
